version: '3.4'

services:
  node-runner:
    env_file:
      - .env
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs
    build:
      context: ./node-runner
      dockerfile: Dockerfile
      args:
        - BINARY_FILE=hyper-v2.6.1-b_linux-arm64
